version: '3'

services:
  apt-cacher-ng:
    restart: always
    image: sameersbn/apt-cacher-ng:3.7.4-24.04
    init: true
    ports:
    - "3142:3142"
    volumes:
    - /srv/docker/apt-cacher-ng:/var/cache/apt-cacher-ng
